version: "3.9"

services:
  url_shortener :
    environment:
      - ENABLE_KEY_SERVICE=true
      - ENDPOINTS.KEY_SERVER.HTTP.HOST=key_generate
      - ENDPOINTS.KEY_SERVER.HTTP.PORT=8080
      - TRACE.ENABLE=true
  kgs-service-build:
    build:
      context: .
      args:
        MAIN_PATH: key_generate
      dockerfile: build/dockerfile
      
    image: key_generate:latest
  key_generate :
    image: key_generate:latest
    ports:  
      - 8080:8080
    environment:
      - DATABASES.HOST=kgs-mysql
      - MIGRATION_FILE_PATH=./pkg/database/migrations
    depends_on:
      - mysql
    restart: always
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.28.0
    ports:
      - 16686:16686
      - 14268:14268
  kgs-mysql:
    image: mysql:latest
    container_name: kgs-mysql
    environment:
      MYSQL_DATABASE: url_shortener
      MYSQL_ROOT_PASSWORD: pass
    command: --lower_case_table_names=0