version: "3.9"

services:
  url_shortener :
    environment:
      - RATELIMIT.ENABLE=true
      - RATELIMIT_REDIS.HOST=redis-ratelimit
      - RATELIMIT_REDIS.PORT=6379
  redis-ratelimit:
    image: redis:6-alpine
    container_name: redis-ratelimit
    command: redis-server --requirepass "pass"  --maxmemory-policy volatile-lru
    platform: linux/amd64